# Site settings
title: The Niche 
email: dan@raloff.net 
description: A simple project site 
baseurl: "" 
url: "http://komon.github.io" # the base hostname & protocol for your site
twitter_username: draloff 
github_username:  komon

# Build settings
markdown: kramdown
